---
title: "writing functions"
author: "Purnima Sharma"
date: "11/8/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,          #aspect ratio: height over width
  out.width = "90%"      # figure doesn't go all the way out on full(100%) page
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis", # to override ggplot default colors.
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Do something simple (finding z-scores!)

```{r}
x_vec = rnorm(30, mean = 5, sd = 3) # create x-vector coming from normal distr, it has 30 numbers

(x_vec - mean(x_vec))/sd(x_vec)  #calculating z-scores of x-vector values
```

Using a function to compute z-scores instead.

```{r}
z_scores = function(x){     #creating function called z-scores, that has input x.
  
  z = (x - mean(x)) / sd(x)    # (body of the function) solve function using input x. Call the solved value z.
  
  return(z)
  
}

z_scores(x_vec)     #operate z-scores function on x-vector(created above:line31). So input is x_vec
```

Updating function so it works on valid inputs only.

```{r}
z_scores = function(x){
  
  if (!is.numeric(x)){              # if x-input is not numeric, stop
    stop("input must be numeric")
  }
  
  if (length(x) < 3){              # input should have alteast 3-values, if not, stop.
    stop("input must have atleast 3 numbers")
  }
  
  z = (x - mean(x)) / sd(x)    
  
  return(z)
  
}

z_scores(x_vec)    
```


